### ISSUE TITLE
Config Loop

### ISSUE THREAD

**Issue by pranktap** [kmdm/hass_anova_cooker#1]
On 11.2021 of HA with HACS installed and I added this as a custom integration. While clicking on integration setup it says "Please wait while ANOVA Precision Cooker is being setup" for a few seconds then says, "Error
Config flow could not be loaded" Any ideas on why?

**Comment by pranktap** [comment]
updated log

**Comment by kmdm** [comment]
Do you have any log entries from the HASS logs showing any errors?

**Comment by kmdm** [comment]
Although to be honest it's probably because the manifest requires aionova==0.0.6 but I haven't pushed/published that due to an oversight. 

Do you have an error about the integration failing to load? 

I'll try to do this over the weekend so at least it'll work as committed!

**Comment by pranktap** [comment]
> Although to be honest it's probably because the manifest requires aionova==0.0.6 but I haven't pushed/published that due to an oversight.
> 
> Do you have an error about the integration failing to load?
> 
> I'll try to do this over the weekend so at least it'll work as committed!

Unable to install package aionova==0.0.6: ERROR: Could not find a version that satisfies the requirement aionova==0.0.6 (from versions: 0.0.5) ERROR: No matching distribution found for aionova==0.0.6 WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command. 

My HA install shows 

Python Version | 3.9.7
-- | --

**Comment by kmdm** [comment]
Fixed in https://github.com/kmdm/aionova/releases/tag/v0.0.6 (released to PyPi) in January /cough
